### ISSUE TITLE
scrollToBottom not working properly

### ISSUE THREAD

**Issue by diegoje** [hellopablo/faketerminal#1]
Hi Pablo, really like what you've done here - I am implementing it on my new personal website.

One issue I've noticed: depending on the content of the output, the scrollToBottom is not done properly. So I end up with some of my text "cut" (see screenshot). Once I start typing, the whole text is visible but it is not as if I had done a clean "enter", with the margin at the bottom.

Do you have the same issue? What could I do to fix this issue?

Thanks!
<img width="897" alt="screen shot 2018-01-22 at 21 34 44" src="https://user-images.githubusercontent.com/16388805/35245743-31f6783c-ffbc-11e7-861f-e60b3953c9e5.png">

**Comment by hellopablo** [comment]
Hey @diegoje - thanks for the kind words! Great to see someone using this.

I don't have the same issue, but happy to try and help! Could you post an example of this happening and I'll have a look? I'm a little busy with the day job just now but will have a look as soon as I can.

*Edit:* This happens in the demo as well - I'll start there.

**Comment by diegoje** [comment]
Awesome, thanks @hellopablo - my guess is on the way it handles scrollTBottom, but I'm really not an expert.

Let me know what you find - I'm interested in learning...

**Comment by da-snap** [comment]
#3 
I came across this repo and thought I can us it for my website. But I can't see the input after a command, so I fixed it.
